# Generated by Django 5.0.1 on 2024-01-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
